// Auto-generated by scripts/generate-sw.mjs — do not edit.
// Offline support for SFX Planner: precaches the app shell so the PDF parser
// (a lazy chunk) and its worker remain reachable when the network is down.
// No planning data, no imported PDFs, no user content is ever stored here —
// only the static files produced by `vite build`.

const CACHE = "sfx-planner-fc72eef02a66";
const PRECACHE = [
  "./assets/html2canvas-DepOADlv-CanBzjR9-Bsx8s7i0.js",
  "./assets/index-C7xz3iQH.js",
  "./assets/index-PZGZ7dAw.css",
  "./assets/index.es-n2jutSem-Bn2F47zt-JsFnPm5h.js",
  "./assets/pdf-DRond7q0-D2vOMqRq-Cu42TDFB.js",
  "./assets/pdf.worker.min-SzY6Yteu-SzY6Yteu-SzY6Yteu.js",
  "./assets/purify.es-BX_3MCif-BiodxAzE-Cy2yYG7j.js",
  "./favicon.svg",
  "./icons.svg",
  "./index.html",
  "./sfx-dragon-logo-dark.png",
  "./sfx-dragon-logo-light.png",
  "./sfx-dragon-logo.jpg"
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Use {cache: 'reload'} so installation always pulls fresh bytes from the
    // network (or HTTP cache) rather than reusing an older SW's response.
    await Promise.all(PRECACHE.map((url) => cache.add(new Request(url, { cache: 'reload' }))));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.map((n) => (n === CACHE ? null : caches.delete(n))));
    await self.clients.claim();
  })());
});

// Cache-first for same-origin GETs inside our scope. Falls back to network,
// and on network failure for navigations returns the cached index.html so
// the SPA still boots offline. Cross-origin requests (Google Fonts, etc.)
// are left to the browser — no opaque caching, no surprises.
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (!url.pathname.startsWith(new URL('./', self.location.href).pathname)) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(req, { ignoreSearch: true });
    if (cached) return cached;
    try {
      const fresh = await fetch(req);
      return fresh;
    } catch (err) {
      if (req.mode === 'navigate') {
        const shell = await cache.match('./index.html');
        if (shell) return shell;
      }
      throw err;
    }
  })());
});
