// Post-build script: walks dist/ and emits dist/sw.js with a versioned list
// of every static asset to precache. The service worker only caches the app
// shell (HTML, JS, CSS, fonts, images, the pdfjs worker and the lazy pdf
// chunk). It never caches imported PDFs or planning data — those stay
// in-memory in the page, exactly like the online build.
//
// Scope: the SW is registered at the same path it is served from, so on
// GitHub Pages (https://<user>.github.io/sfx-planner/sw.js) its scope is
// `/sfx-planner/` and all precached URLs are relative (`./assets/...`,
// `./index.html`) — matching Vite's `base: './'`.

import { readdirSync, statSync, writeFileSync, readFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { createHash } from 'node:crypto';

const DIST = new URL('../dist/', import.meta.url).pathname;

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      out.push(...walk(full));
    } else if (st.isFile()) {
      out.push(full);
    }
  }
  return out;
}

const files = walk(DIST)
  .map((p) => relative(DIST, p).split(sep).join('/'))
  // Don't precache the SW itself or any previous SW build artefacts.
  .filter((p) => p !== 'sw.js')
  .sort();

// Stable cache version derived from the contents of every precached file.
const hash = createHash('sha256');
for (const rel of files) {
  hash.update(rel);
  hash.update('\0');
  hash.update(readFileSync(join(DIST, rel)));
  hash.update('\0');
}
const CACHE_VERSION = hash.digest('hex').slice(0, 12);
const CACHE_NAME = `sfx-planner-${CACHE_VERSION}`;

const precacheList = files.map((f) => `./${f}`);

const sw = `// Auto-generated by scripts/generate-sw.mjs — do not edit.
// Offline support for SFX Planner: precaches the app shell so the PDF parser
// (a lazy chunk) and its worker remain reachable when the network is down.
// No planning data, no imported PDFs, no user content is ever stored here —
// only the static files produced by \`vite build\`.

const CACHE = ${JSON.stringify(CACHE_NAME)};
const PRECACHE = ${JSON.stringify(precacheList, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Use {cache: 'reload'} so installation always pulls fresh bytes from the
    // network (or HTTP cache) rather than reusing an older SW's response.
    await Promise.all(PRECACHE.map((url) => cache.add(new Request(url, { cache: 'reload' }))));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.map((n) => (n === CACHE ? null : caches.delete(n))));
    await self.clients.claim();
  })());
});

// Cache-first for same-origin GETs inside our scope. Falls back to network,
// and on network failure for navigations returns the cached index.html so
// the SPA still boots offline. Cross-origin requests (Google Fonts, etc.)
// are left to the browser — no opaque caching, no surprises.
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (!url.pathname.startsWith(new URL('./', self.location.href).pathname)) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(req, { ignoreSearch: true });
    if (cached) return cached;
    try {
      const fresh = await fetch(req);
      return fresh;
    } catch (err) {
      if (req.mode === 'navigate') {
        const shell = await cache.match('./index.html');
        if (shell) return shell;
      }
      throw err;
    }
  })());
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);
console.log(`[generate-sw] wrote dist/sw.js — cache ${CACHE_NAME} with ${files.length} files`);
